title: Lalatainer | your trustworthy ffxiv's retainer.
email: lalatainer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  FFXIV farming services | totem run | title&archievement | mount farming
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lalatainer.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

